
package agendamiento;

import java.awt.Color;

/**
 *
 * @author Xelan
 */
public class GUI extends javax.swing.JFrame {
GestorUsuario gestor;
Paciente paciente;
Doctor doc;
Administrador admin;
    /**
     * Creates new form GUI
     */
    public GUI() {
        gestor= new GestorUsuario();
        
        initComponents();
        RegistroP.hide();
        RegistroExitosoP.hide();
        DocIntP.hide();
        AdmIntP.hide();
        UserIntP.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baseP = new javax.swing.JPanel();
        UserIntP = new javax.swing.JPanel();
        UserMenuP = new javax.swing.JPanel();
        nuevaCitaB = new javax.swing.JButton();
        cambiarCitaB = new javax.swing.JButton();
        eliminarCitaB = new javax.swing.JButton();
        consultarCitaB = new javax.swing.JButton();
        userVolverB = new javax.swing.JButton();
        BaseUserP = new javax.swing.JPanel();
        CambiarCitaP = new javax.swing.JPanel();
        actDiaBox = new javax.swing.JComboBox<>();
        horaActL = new javax.swing.JLabel();
        actHoraBox = new javax.swing.JComboBox<>();
        actMinL = new javax.swing.JLabel();
        actMinBox = new javax.swing.JComboBox<>();
        actDiaL = new javax.swing.JLabel();
        modDiaBox = new javax.swing.JComboBox<>();
        modHoraL = new javax.swing.JLabel();
        modHoraBox = new javax.swing.JComboBox<>();
        modMinL = new javax.swing.JLabel();
        modMinBox = new javax.swing.JComboBox<>();
        modDiaL = new javax.swing.JLabel();
        modL = new javax.swing.JLabel();
        actL = new javax.swing.JLabel();
        modificarB = new javax.swing.JButton();
        titleModL = new javax.swing.JLabel();
        NuevaCitaP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        seleccioneL = new javax.swing.JLabel();
        diaL = new javax.swing.JLabel();
        diaNuevaBox = new javax.swing.JComboBox<>();
        horaNewL = new javax.swing.JLabel();
        horaNewBox = new javax.swing.JComboBox<>();
        minNewL = new javax.swing.JLabel();
        minNewBox = new javax.swing.JComboBox<>();
        agendarB = new javax.swing.JButton();
        imagenUserL = new javax.swing.JLabel();
        AdmIntP = new javax.swing.JPanel();
        UserMenuP2 = new javax.swing.JPanel();
        admVolverB = new javax.swing.JButton();
        BaseUserP2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        admGeneraB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        InicioP = new javax.swing.JPanel();
        menuInL = new javax.swing.JPanel();
        ingresoL = new javax.swing.JLabel();
        tipoBox = new javax.swing.JComboBox<>();
        tipoL = new javax.swing.JLabel();
        codL = new javax.swing.JLabel();
        codTxt = new javax.swing.JTextField();
        passL = new javax.swing.JLabel();
        passTxt = new javax.swing.JTextField();
        ingresarB = new javax.swing.JButton();
        nuevoP = new javax.swing.JPanel();
        nuevoUserL = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        fondoInicioL = new javax.swing.JLabel();
        BarraSuperiorP = new javax.swing.JPanel();
        nameOrgL = new javax.swing.JLabel();
        RegistroP = new javax.swing.JPanel();
        menuRegP = new javax.swing.JPanel();
        registroDeL = new javax.swing.JLabel();
        tipoRegBox = new javax.swing.JComboBox<>();
        cedulaL = new javax.swing.JLabel();
        ApellidosL = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        apellidosTxt = new javax.swing.JTextField();
        nombresL = new javax.swing.JLabel();
        telefonoL = new javax.swing.JLabel();
        cedulaTxt = new javax.swing.JTextField();
        telefonoTxt = new javax.swing.JTextField();
        emailL = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        contra = new javax.swing.JLabel();
        contraTxt = new javax.swing.JTextField();
        verifContrL = new javax.swing.JLabel();
        verifContTxt = new javax.swing.JTextField();
        codverifL = new javax.swing.JLabel();
        codverifTxt = new javax.swing.JTextField();
        registrarB = new javax.swing.JButton();
        regresarB = new javax.swing.JButton();
        errorRegistroL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        RegistroExitosoP = new javax.swing.JPanel();
        menuExitoP = new javax.swing.JPanel();
        agradecimientoL = new javax.swing.JLabel();
        suCodesL = new javax.swing.JLabel();
        variableDadaTxt = new javax.swing.JTextField();
        volverB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        DocIntP = new javax.swing.JPanel();
        UserMenuP1 = new javax.swing.JPanel();
        docVolverB = new javax.swing.JButton();
        BaseUserP1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        baseP.setBackground(new java.awt.Color(255, 255, 255));
        baseP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserIntP.setBackground(new java.awt.Color(255, 204, 204));
        UserIntP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserMenuP.setBackground(new java.awt.Color(255, 255, 255));
        UserMenuP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nuevaCitaB.setBackground(new java.awt.Color(102, 153, 255));
        nuevaCitaB.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        nuevaCitaB.setForeground(new java.awt.Color(255, 255, 255));
        nuevaCitaB.setText("Nueva cita");
        nuevaCitaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaCitaBActionPerformed(evt);
            }
        });
        UserMenuP.add(nuevaCitaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 44, 117, 43));

        cambiarCitaB.setBackground(new java.awt.Color(102, 153, 255));
        cambiarCitaB.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        cambiarCitaB.setForeground(new java.awt.Color(255, 255, 255));
        cambiarCitaB.setText("Cambiar cita");
        cambiarCitaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarCitaBActionPerformed(evt);
            }
        });
        UserMenuP.add(cambiarCitaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 105, 117, 43));

        eliminarCitaB.setBackground(new java.awt.Color(102, 153, 255));
        eliminarCitaB.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        eliminarCitaB.setForeground(new java.awt.Color(255, 255, 255));
        eliminarCitaB.setText("Eliminar cita");
        UserMenuP.add(eliminarCitaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 166, 117, 43));

        consultarCitaB.setBackground(new java.awt.Color(102, 153, 255));
        consultarCitaB.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        consultarCitaB.setForeground(new java.awt.Color(255, 255, 255));
        consultarCitaB.setText("Consulta citas");
        consultarCitaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarCitaBActionPerformed(evt);
            }
        });
        UserMenuP.add(consultarCitaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 221, 117, 43));

        userVolverB.setBackground(new java.awt.Color(102, 153, 255));
        userVolverB.setForeground(new java.awt.Color(255, 255, 255));
        userVolverB.setText("Volver");
        userVolverB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userVolverBActionPerformed(evt);
            }
        });
        UserMenuP.add(userVolverB, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 402, 117, -1));

        UserIntP.add(UserMenuP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 450));

        BaseUserP.setBackground(new java.awt.Color(255, 255, 255));
        BaseUserP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CambiarCitaP.setBackground(new java.awt.Color(255, 255, 255));

        actDiaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado" }));

        horaActL.setForeground(new java.awt.Color(153, 153, 153));
        horaActL.setText("Hora");

        actHoraBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "8h", "9h", "10h", "11h", "12h", "3h", "4h", "5h" }));

        actMinL.setForeground(new java.awt.Color(153, 153, 153));
        actMinL.setText("Minutos");

        actMinBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecccione", ":00", ":30" }));

        actDiaL.setForeground(new java.awt.Color(153, 153, 153));
        actDiaL.setText("Día");

        modDiaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado" }));

        modHoraL.setForeground(new java.awt.Color(153, 153, 153));
        modHoraL.setText("Hora");

        modHoraBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "8h", "9h", "10h", "11h", "12h", "3h", "4h", "5h" }));

        modMinL.setForeground(new java.awt.Color(153, 153, 153));
        modMinL.setText("Minutos");

        modMinBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecccione", ":00", ":30" }));

        modDiaL.setForeground(new java.awt.Color(153, 153, 153));
        modDiaL.setText("Día");

        modL.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        modL.setForeground(new java.awt.Color(153, 153, 153));
        modL.setText("Cita nueva");

        actL.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        actL.setForeground(new java.awt.Color(153, 153, 153));
        actL.setText("Cita actual");

        modificarB.setBackground(new java.awt.Color(102, 153, 255));
        modificarB.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        modificarB.setForeground(new java.awt.Color(255, 255, 255));
        modificarB.setText("Modificar cita");

        titleModL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleModL.setForeground(new java.awt.Color(102, 153, 255));
        titleModL.setText("Cambio cita");

        javax.swing.GroupLayout CambiarCitaPLayout = new javax.swing.GroupLayout(CambiarCitaP);
        CambiarCitaP.setLayout(CambiarCitaPLayout);
        CambiarCitaPLayout.setHorizontalGroup(
            CambiarCitaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CambiarCitaPLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(CambiarCitaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actDiaL)
                    .addComponent(horaActL)
                    .addComponent(actMinL)
                    .addGroup(CambiarCitaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(actMinBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(actHoraBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(actDiaBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(actL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(CambiarCitaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modDiaL)
                    .addComponent(modHoraL)
                    .addComponent(modMinL)
                    .addGroup(CambiarCitaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(modMinBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modHoraBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modDiaBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(modL))
                .addGap(46, 46, 46))
            .addGroup(CambiarCitaPLayout.createSequentialGroup()
                .addGroup(CambiarCitaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CambiarCitaPLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(modificarB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CambiarCitaPLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(titleModL)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CambiarCitaPLayout.setVerticalGroup(
            CambiarCitaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CambiarCitaPLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(titleModL)
                .addGap(18, 18, 18)
                .addGroup(CambiarCitaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actL)
                    .addComponent(modL))
                .addGap(31, 31, 31)
                .addGroup(CambiarCitaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CambiarCitaPLayout.createSequentialGroup()
                        .addComponent(modDiaL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modDiaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modHoraL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modHoraBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modMinL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modMinBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CambiarCitaPLayout.createSequentialGroup()
                        .addComponent(actDiaL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actDiaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(horaActL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actHoraBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(actMinL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actMinBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(modificarB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        BaseUserP.add(CambiarCitaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 560, 410));

        NuevaCitaP.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setForeground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Hora:", "Disponible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        seleccioneL.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        seleccioneL.setForeground(new java.awt.Color(153, 153, 153));
        seleccioneL.setText("Selecciones día y hora de la cita");

        diaL.setForeground(new java.awt.Color(153, 153, 153));
        diaL.setText("Día");

        diaNuevaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado" }));

        horaNewL.setForeground(new java.awt.Color(153, 153, 153));
        horaNewL.setText("Hora");

        horaNewBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "8h", "9h", "10h", "11h", "12h", "3h", "4h", "5h" }));

        minNewL.setForeground(new java.awt.Color(153, 153, 153));
        minNewL.setText("Minutos");

        minNewBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecccione", ":00", ":30" }));

        agendarB.setBackground(new java.awt.Color(153, 204, 255));
        agendarB.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        agendarB.setForeground(new java.awt.Color(255, 255, 255));
        agendarB.setText("Agendar");

        javax.swing.GroupLayout NuevaCitaPLayout = new javax.swing.GroupLayout(NuevaCitaP);
        NuevaCitaP.setLayout(NuevaCitaPLayout);
        NuevaCitaPLayout.setHorizontalGroup(
            NuevaCitaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NuevaCitaPLayout.createSequentialGroup()
                .addGroup(NuevaCitaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NuevaCitaPLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(NuevaCitaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seleccioneL)
                            .addComponent(diaL)
                            .addComponent(horaNewL)
                            .addComponent(minNewL)
                            .addGroup(NuevaCitaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(minNewBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 191, Short.MAX_VALUE)
                                .addComponent(horaNewBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(diaNuevaBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(NuevaCitaPLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(agendarB, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        NuevaCitaPLayout.setVerticalGroup(
            NuevaCitaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NuevaCitaPLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(NuevaCitaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NuevaCitaPLayout.createSequentialGroup()
                        .addComponent(seleccioneL)
                        .addGap(26, 26, 26)
                        .addComponent(diaL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diaNuevaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(horaNewL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(horaNewBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(minNewL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minNewBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(agendarB, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        BaseUserP.add(NuevaCitaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 560, 410));

        imagenUserL.setBackground(new java.awt.Color(204, 204, 255));
        imagenUserL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/baseUser2.jpeg"))); // NOI18N
        BaseUserP.add(imagenUserL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        UserIntP.add(BaseUserP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 670, 450));

        baseP.add(UserIntP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, 820, 450));

        AdmIntP.setBackground(new java.awt.Color(255, 204, 204));
        AdmIntP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserMenuP2.setBackground(new java.awt.Color(255, 255, 255));
        UserMenuP2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admVolverB.setBackground(new java.awt.Color(102, 153, 255));
        admVolverB.setForeground(new java.awt.Color(255, 255, 255));
        admVolverB.setText("Volver");
        admVolverB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admVolverBMouseClicked(evt);
            }
        });
        admVolverB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admVolverBActionPerformed(evt);
            }
        });
        UserMenuP2.add(admVolverB, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 402, 117, -1));

        AdmIntP.add(UserMenuP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 450));

        BaseUserP2.setBackground(new java.awt.Color(255, 255, 255));
        BaseUserP2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 153, 255));
        jLabel5.setText("Generar nuevo Horario");

        admGeneraB.setBackground(new java.awt.Color(102, 153, 255));
        admGeneraB.setForeground(new java.awt.Color(255, 255, 255));
        admGeneraB.setText("Generar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(84, 84, 84))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(admGeneraB, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addGap(57, 57, 57)
                .addComponent(admGeneraB, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        BaseUserP2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 360, 240));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/how-to-become-medical-assistant.jpg"))); // NOI18N
        BaseUserP2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, -1, -1));

        AdmIntP.add(BaseUserP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 670, 450));

        baseP.add(AdmIntP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, 820, 450));

        InicioP.setBackground(new java.awt.Color(255, 204, 204));
        InicioP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuInL.setBackground(new java.awt.Color(255, 255, 255));

        ingresoL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ingresoL.setForeground(new java.awt.Color(102, 153, 255));
        ingresoL.setText("INGRESO");

        tipoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Paciente", "Doctor", "Administrador" }));

        tipoL.setForeground(new java.awt.Color(153, 153, 153));
        tipoL.setText("Tipo");

        codL.setForeground(new java.awt.Color(153, 153, 153));
        codL.setText("Código usuario");

        codTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codTxtActionPerformed(evt);
            }
        });

        passL.setForeground(new java.awt.Color(153, 153, 153));
        passL.setText("Contraseña");

        ingresarB.setBackground(new java.awt.Color(102, 153, 255));
        ingresarB.setForeground(new java.awt.Color(255, 255, 255));
        ingresarB.setText("Ingresar");
        ingresarB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarBMouseClicked(evt);
            }
        });
        ingresarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarBActionPerformed(evt);
            }
        });

        nuevoP.setBackground(new java.awt.Color(255, 255, 255));
        nuevoP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoPMouseClicked(evt);
            }
        });

        nuevoUserL.setBackground(new java.awt.Color(102, 153, 255));
        nuevoUserL.setForeground(new java.awt.Color(102, 153, 255));
        nuevoUserL.setText("Nuevo usuario");

        javax.swing.GroupLayout nuevoPLayout = new javax.swing.GroupLayout(nuevoP);
        nuevoP.setLayout(nuevoPLayout);
        nuevoPLayout.setHorizontalGroup(
            nuevoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoPLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(nuevoUserL)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        nuevoPLayout.setVerticalGroup(
            nuevoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nuevoUserL)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        a.setForeground(new java.awt.Color(255, 255, 255));
        a.setText("contraseña o usuario incorrecto");

        javax.swing.GroupLayout menuInLLayout = new javax.swing.GroupLayout(menuInL);
        menuInL.setLayout(menuInLLayout);
        menuInLLayout.setHorizontalGroup(
            menuInLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuInLLayout.createSequentialGroup()
                .addGroup(menuInLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuInLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuInLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(codTxt)
                            .addGroup(menuInLLayout.createSequentialGroup()
                                .addGroup(menuInLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ingresoL)
                                    .addComponent(tipoL)
                                    .addComponent(codL)
                                    .addComponent(passL))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(passTxt)))
                    .addGroup(menuInLLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(ingresarB)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuInLLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nuevoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(menuInLLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(a)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        menuInLLayout.setVerticalGroup(
            menuInLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuInLLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ingresoL)
                .addGap(7, 7, 7)
                .addComponent(tipoL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(codL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(a)
                .addGap(12, 12, 12)
                .addComponent(ingresarB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuevoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        InicioP.add(menuInL, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 290, 330));

        fondoInicioL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/baseInicioAgendamiento.jpg"))); // NOI18N
        InicioP.add(fondoInicioL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -110, 960, 680));

        baseP.add(InicioP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, 820, 450));

        BarraSuperiorP.setBackground(new java.awt.Color(153, 204, 255));

        nameOrgL.setBackground(new java.awt.Color(255, 255, 255));
        nameOrgL.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        nameOrgL.setForeground(new java.awt.Color(255, 255, 255));
        nameOrgL.setText("MEDIJUNTOS");

        javax.swing.GroupLayout BarraSuperiorPLayout = new javax.swing.GroupLayout(BarraSuperiorP);
        BarraSuperiorP.setLayout(BarraSuperiorPLayout);
        BarraSuperiorPLayout.setHorizontalGroup(
            BarraSuperiorPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraSuperiorPLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(nameOrgL, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(983, Short.MAX_VALUE))
        );
        BarraSuperiorPLayout.setVerticalGroup(
            BarraSuperiorPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraSuperiorPLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(nameOrgL, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        baseP.add(BarraSuperiorP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 80));

        RegistroP.setBackground(new java.awt.Color(255, 204, 204));
        RegistroP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuRegP.setBackground(new java.awt.Color(255, 255, 255));

        registroDeL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registroDeL.setForeground(new java.awt.Color(102, 153, 255));
        registroDeL.setText("Registro de: ");

        tipoRegBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Paciente", "Doctor", "Administrador" }));
        tipoRegBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoRegBoxActionPerformed(evt);
            }
        });

        cedulaL.setForeground(new java.awt.Color(153, 153, 153));
        cedulaL.setText("Cédula o pasaporte");

        ApellidosL.setForeground(new java.awt.Color(153, 153, 153));
        ApellidosL.setText("Apellidos");

        nombresL.setForeground(new java.awt.Color(153, 153, 153));
        nombresL.setText("Nombres");

        telefonoL.setForeground(new java.awt.Color(153, 153, 153));
        telefonoL.setText("Teléfono o celular");

        emailL.setForeground(new java.awt.Color(153, 153, 153));
        emailL.setText("e-mail");

        contra.setForeground(new java.awt.Color(153, 153, 153));
        contra.setText("Contraseña");

        verifContrL.setForeground(new java.awt.Color(153, 153, 153));
        verifContrL.setText("Ingrese nuevamente contraseña");

        codverifL.setForeground(new java.awt.Color(153, 153, 153));
        codverifL.setText("Cod. Verificación (si es paciente deje el cuadro en blanco)");

        registrarB.setBackground(new java.awt.Color(102, 153, 255));
        registrarB.setForeground(new java.awt.Color(255, 255, 255));
        registrarB.setText("Registrar");
        registrarB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarBMouseClicked(evt);
            }
        });

        regresarB.setForeground(new java.awt.Color(102, 153, 255));
        regresarB.setText("Regresar");
        regresarB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarBMouseClicked(evt);
            }
        });

        errorRegistroL.setForeground(new java.awt.Color(255, 255, 255));
        errorRegistroL.setText("Error de Ingreso");

        javax.swing.GroupLayout menuRegPLayout = new javax.swing.GroupLayout(menuRegP);
        menuRegP.setLayout(menuRegPLayout);
        menuRegPLayout.setHorizontalGroup(
            menuRegPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuRegPLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(menuRegPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuRegPLayout.createSequentialGroup()
                        .addGroup(menuRegPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuRegPLayout.createSequentialGroup()
                                .addComponent(registroDeL)
                                .addGap(18, 18, 18)
                                .addComponent(tipoRegBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuRegPLayout.createSequentialGroup()
                                .addGroup(menuRegPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cedulaL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(menuRegPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telefonoL)
                                    .addComponent(apellidosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(39, 39, 39))
                    .addGroup(menuRegPLayout.createSequentialGroup()
                        .addComponent(nombresL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ApellidosL)
                        .addGap(184, 184, 184))
                    .addGroup(menuRegPLayout.createSequentialGroup()
                        .addGroup(menuRegPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailL)
                            .addComponent(cedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailTxt))
                        .addGap(39, 39, 39))
                    .addGroup(menuRegPLayout.createSequentialGroup()
                        .addComponent(contra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(verifContrL)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuRegPLayout.createSequentialGroup()
                        .addGroup(menuRegPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuRegPLayout.createSequentialGroup()
                                .addComponent(contraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(verifContTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuRegPLayout.createSequentialGroup()
                                .addGroup(menuRegPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codverifL)
                                    .addGroup(menuRegPLayout.createSequentialGroup()
                                        .addComponent(regresarB)
                                        .addGap(85, 85, 85)
                                        .addComponent(errorRegistroL)))
                                .addGroup(menuRegPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(menuRegPLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(registrarB, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                                    .addGroup(menuRegPLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(codverifTxt)))))
                        .addGap(38, 38, 38))))
        );
        menuRegPLayout.setVerticalGroup(
            menuRegPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuRegPLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(menuRegPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registroDeL)
                    .addComponent(tipoRegBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menuRegPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApellidosL)
                    .addComponent(nombresL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuRegPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menuRegPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaL)
                    .addComponent(telefonoL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuRegPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuRegPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contra)
                    .addComponent(verifContrL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuRegPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verifContTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menuRegPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codverifL)
                    .addComponent(codverifTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menuRegPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regresarB)
                    .addComponent(errorRegistroL))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        RegistroP.add(menuRegP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 480, 400));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pacienteLabel.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        RegistroP.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, -1, -1));

        baseP.add(RegistroP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, 820, 450));

        RegistroExitosoP.setBackground(new java.awt.Color(255, 255, 255));
        RegistroExitosoP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuExitoP.setBackground(new java.awt.Color(153, 204, 255));

        agradecimientoL.setBackground(new java.awt.Color(255, 255, 255));
        agradecimientoL.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        agradecimientoL.setForeground(new java.awt.Color(255, 255, 255));
        agradecimientoL.setText("Gracias por unirse a nuestra familia");

        suCodesL.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        suCodesL.setForeground(new java.awt.Color(255, 255, 255));
        suCodesL.setText("Su código de usuario es:");

        variableDadaTxt.setEditable(false);

        volverB.setBackground(new java.awt.Color(102, 153, 255));
        volverB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        volverB.setForeground(new java.awt.Color(255, 255, 255));
        volverB.setText("Volver");
        volverB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuExitoPLayout = new javax.swing.GroupLayout(menuExitoP);
        menuExitoP.setLayout(menuExitoPLayout);
        menuExitoPLayout.setHorizontalGroup(
            menuExitoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuExitoPLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(menuExitoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuExitoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuExitoPLayout.createSequentialGroup()
                            .addComponent(suCodesL)
                            .addGap(102, 102, 102))
                        .addGroup(menuExitoPLayout.createSequentialGroup()
                            .addComponent(agradecimientoL)
                            .addGap(20, 20, 20)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuExitoPLayout.createSequentialGroup()
                        .addComponent(volverB)
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuExitoPLayout.createSequentialGroup()
                        .addComponent(variableDadaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))))
        );
        menuExitoPLayout.setVerticalGroup(
            menuExitoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuExitoPLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(agradecimientoL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(suCodesL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(variableDadaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(volverB)
                .addGap(19, 19, 19))
        );

        RegistroExitosoP.add(menuExitoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 420, 200));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pestelog.jpg"))); // NOI18N
        RegistroExitosoP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 340, -1));

        baseP.add(RegistroExitosoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, 820, 450));

        DocIntP.setBackground(new java.awt.Color(255, 204, 204));
        DocIntP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserMenuP1.setBackground(new java.awt.Color(255, 255, 255));
        UserMenuP1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        docVolverB.setBackground(new java.awt.Color(102, 153, 255));
        docVolverB.setForeground(new java.awt.Color(255, 255, 255));
        docVolverB.setText("Volver");
        docVolverB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docVolverBMouseClicked(evt);
            }
        });
        docVolverB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docVolverBActionPerformed(evt);
            }
        });
        UserMenuP1.add(docVolverB, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 402, 117, -1));

        DocIntP.add(UserMenuP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 450));

        BaseUserP1.setBackground(new java.awt.Color(255, 255, 255));
        BaseUserP1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sitio-web-en-mantenimientoa.jpg"))); // NOI18N
        BaseUserP1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        DocIntP.add(BaseUserP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 670, 450));

        baseP.add(DocIntP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, 820, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baseP, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baseP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codTxtActionPerformed

    private void nuevoPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoPMouseClicked
InicioP.hide();
codTxt.setText("");
passTxt.setText("");
apellidosTxt.setText("");
nombreTxt.setText("");
cedulaTxt.setText("");
emailTxt.setText("");
telefonoTxt.setText("");
contraTxt.setText("");
verifContTxt.setText("");
codverifTxt.setText("");
variableDadaTxt.setEditable(true);
variableDadaTxt.setText("");
variableDadaTxt.setEditable(false);
RegistroP.show();

    }//GEN-LAST:event_nuevoPMouseClicked

    private void regresarBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarBMouseClicked
RegistroP.hide();
apellidosTxt.setText("");
nombreTxt.setText("");
cedulaTxt.setText("");
emailTxt.setText("");
telefonoTxt.setText("");
contraTxt.setText("");
verifContTxt.setText("");
codverifTxt.setText("");
variableDadaTxt.setEditable(true);
variableDadaTxt.setText("");
variableDadaTxt.setEditable(false);
InicioP.show();
    }//GEN-LAST:event_regresarBMouseClicked

    private void volverBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverBMouseClicked
       RegistroExitosoP.hide();
       InicioP.show();
    }//GEN-LAST:event_volverBMouseClicked

    
    private void registrarBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarBMouseClicked
        boolean permiso=true;
        String textoBox= tipoRegBox.getEditor().getItem().toString();
        if ("Paciente".equals(textoBox)||"Doctor".equals(textoBox)||"Administrador".equals(textoBox)){
            if("".equals(apellidosTxt.getText())||"".equals(nombreTxt.getText())){permiso=false;}
            if("".equals(cedulaTxt.getText())||"".equals(emailTxt.getText())){permiso=false;}
            if("".equals(telefonoTxt.getText())||"".equals(contraTxt.getText())){permiso=false;}
            if("".equals(verifContTxt.getText())){permiso=false;}
            if(!contraTxt.getText().equals(verifContTxt.getText())){permiso=false;}
           
            if(permiso){
            if("Doctor".equals(textoBox)||"Administrador".equals(textoBox)){
            if(!"admin".equals(codverifTxt.getText())){permiso=false;}}
            }
        }else{permiso=false;}
        if(permiso){
            
            registrar(nombreTxt.getText(),apellidosTxt.getText(),cedulaTxt.getText(),telefonoTxt.getText(),emailTxt.getText(), contraTxt.getText(),textoBox);
            
            RegistroP.hide();
            RegistroExitosoP.show();
            errorRegistroL.setForeground(Color.white);
        }else{errorRegistroL.setForeground(Color.red);}
    }//GEN-LAST:event_registrarBMouseClicked
    
    private void registrar(String nombre, String apellidos, String cedula, String telefono, String email, String contraseña, String tipo){
        if(tipo.equals("Doctor")){
            String tex=gestor.crearDoctor(nombre, apellidos, cedula, telefono, email, contraseña);
            variableDadaTxt.setEditable(true);
            variableDadaTxt.setText(tex);
            variableDadaTxt.setEditable(false);
        }else if(tipo.equals("Administrador")){
            String tex=gestor.crearAdmin(nombre, apellidos, cedula, telefono, email, contraseña);
            variableDadaTxt.setEditable(true);
            variableDadaTxt.setText(tex);
            variableDadaTxt.setEditable(false);
        }else{
            String tex=gestor.crearPaciente(nombre, apellidos, cedula, telefono, email, contraseña);
            variableDadaTxt.setEditable(true);
            variableDadaTxt.setText(tex);
            variableDadaTxt.setEditable(false);
        }
    }
    private void tipoRegBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoRegBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoRegBoxActionPerformed

    private void nuevaCitaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaCitaBActionPerformed
      CambiarCitaP.hide();
      NuevaCitaP.show();
    }//GEN-LAST:event_nuevaCitaBActionPerformed

    private void consultarCitaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarCitaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarCitaBActionPerformed

    private void userVolverBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userVolverBActionPerformed
    UserIntP.hide();
    codTxt.setText("");
    passTxt.setText("");
    InicioP.show();
    }//GEN-LAST:event_userVolverBActionPerformed

    private void ingresarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarBActionPerformed

    
    // TODO add your handling code here:
    }//GEN-LAST:event_ingresarBActionPerformed

    private void cambiarCitaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarCitaBActionPerformed
      NuevaCitaP.hide();
      CambiarCitaP.show();
    }//GEN-LAST:event_cambiarCitaBActionPerformed

   
    private void ingresarBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarBMouseClicked
        boolean paso= true;
        String texto= tipoBox.getEditor().getItem().toString();
      
        if(texto.equals("Paciente")||texto.equals("Doctor")||texto.equals("Administrador")){
           
           if(texto.equals("Paciente")){
              paciente=  gestor.encontrarPaciente(codTxt.getText(), passTxt.getText());
             if(paciente!=null) {
                 InicioP.hide();
                 codTxt.setText("");
                 passTxt.setText("");
                 UserIntP.show();
             }
           }else{}
           if (texto.equals("Doctor")){
                doc=  gestor.encontrarDoc(codTxt.getText(), passTxt.getText());
             if(doc!=null) {
                 InicioP.hide();
                 codTxt.setText("");
                 passTxt.setText("");
                 DocIntP.show();
             }
           }
           if(texto.equals("Administrador")){
               System.out.println("hola");
               admin= gestor.encontrarAdmin(codTxt.getText(),passTxt.getText());
               if(admin!=null){
                 InicioP.hide();
                 codTxt.setText("");
                 passTxt.setText("");
                 AdmIntP.show();   
               }
           }
        }
    }//GEN-LAST:event_ingresarBMouseClicked

    private void docVolverBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docVolverBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docVolverBActionPerformed

    private void docVolverBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docVolverBMouseClicked
    DocIntP.hide();
    codTxt.setText("");
    passTxt.setText("");
    InicioP.show();
    }//GEN-LAST:event_docVolverBMouseClicked

    private void admVolverBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admVolverBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admVolverBActionPerformed

    private void admVolverBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admVolverBMouseClicked
    AdmIntP.hide();
    codTxt.setText("");
    passTxt.setText("");
    InicioP.show();
    }//GEN-LAST:event_admVolverBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdmIntP;
    private javax.swing.JLabel ApellidosL;
    private javax.swing.JPanel BarraSuperiorP;
    private javax.swing.JPanel BaseUserP;
    private javax.swing.JPanel BaseUserP1;
    private javax.swing.JPanel BaseUserP2;
    private javax.swing.JPanel CambiarCitaP;
    private javax.swing.JPanel DocIntP;
    private javax.swing.JPanel InicioP;
    private javax.swing.JPanel NuevaCitaP;
    private javax.swing.JPanel RegistroExitosoP;
    private javax.swing.JPanel RegistroP;
    private javax.swing.JPanel UserIntP;
    private javax.swing.JPanel UserMenuP;
    private javax.swing.JPanel UserMenuP1;
    private javax.swing.JPanel UserMenuP2;
    private javax.swing.JLabel a;
    private javax.swing.JComboBox<String> actDiaBox;
    private javax.swing.JLabel actDiaL;
    private javax.swing.JComboBox<String> actHoraBox;
    private javax.swing.JLabel actL;
    private javax.swing.JComboBox<String> actMinBox;
    private javax.swing.JLabel actMinL;
    private javax.swing.JButton admGeneraB;
    private javax.swing.JButton admVolverB;
    private javax.swing.JButton agendarB;
    private javax.swing.JLabel agradecimientoL;
    private javax.swing.JTextField apellidosTxt;
    private javax.swing.JPanel baseP;
    private javax.swing.JButton cambiarCitaB;
    private javax.swing.JLabel cedulaL;
    private javax.swing.JTextField cedulaTxt;
    private javax.swing.JLabel codL;
    private javax.swing.JTextField codTxt;
    private javax.swing.JLabel codverifL;
    private javax.swing.JTextField codverifTxt;
    private javax.swing.JButton consultarCitaB;
    private javax.swing.JLabel contra;
    private javax.swing.JTextField contraTxt;
    private javax.swing.JLabel diaL;
    private javax.swing.JComboBox<String> diaNuevaBox;
    private javax.swing.JButton docVolverB;
    private javax.swing.JButton eliminarCitaB;
    private javax.swing.JLabel emailL;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel errorRegistroL;
    private javax.swing.JLabel fondoInicioL;
    private javax.swing.JLabel horaActL;
    private javax.swing.JComboBox<String> horaNewBox;
    private javax.swing.JLabel horaNewL;
    private javax.swing.JLabel imagenUserL;
    private javax.swing.JButton ingresarB;
    private javax.swing.JLabel ingresoL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel menuExitoP;
    private javax.swing.JPanel menuInL;
    private javax.swing.JPanel menuRegP;
    private javax.swing.JComboBox<String> minNewBox;
    private javax.swing.JLabel minNewL;
    private javax.swing.JComboBox<String> modDiaBox;
    private javax.swing.JLabel modDiaL;
    private javax.swing.JComboBox<String> modHoraBox;
    private javax.swing.JLabel modHoraL;
    private javax.swing.JLabel modL;
    private javax.swing.JComboBox<String> modMinBox;
    private javax.swing.JLabel modMinL;
    private javax.swing.JButton modificarB;
    private javax.swing.JLabel nameOrgL;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JLabel nombresL;
    private javax.swing.JButton nuevaCitaB;
    private javax.swing.JPanel nuevoP;
    private javax.swing.JLabel nuevoUserL;
    private javax.swing.JLabel passL;
    private javax.swing.JTextField passTxt;
    private javax.swing.JButton registrarB;
    private javax.swing.JLabel registroDeL;
    private javax.swing.JButton regresarB;
    private javax.swing.JLabel seleccioneL;
    private javax.swing.JLabel suCodesL;
    private javax.swing.JLabel telefonoL;
    private javax.swing.JTextField telefonoTxt;
    private javax.swing.JComboBox<String> tipoBox;
    private javax.swing.JLabel tipoL;
    private javax.swing.JComboBox<String> tipoRegBox;
    private javax.swing.JLabel titleModL;
    private javax.swing.JButton userVolverB;
    private javax.swing.JTextField variableDadaTxt;
    private javax.swing.JTextField verifContTxt;
    private javax.swing.JLabel verifContrL;
    private javax.swing.JButton volverB;
    // End of variables declaration//GEN-END:variables
}
